import type { Metadata } from "next"
import "../globals.css"
import { Outfit } from "next/font/google"
import { NextIntlClientProvider } from "next-intl"
import { getMessages } from "next-intl/server" // Ensure this function is correctly implemented
import { routing } from "@/i18n/routing"
import { unstable_setRequestLocale } from "next-intl/server"

// PrimeReact CSS imports
import "primereact/resources/themes/saga-blue/theme.css" // Theme (or any other theme you're using)

// Components
import Navbar from "../components/Navbar"

const outfit = Outfit({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

// Generate static params for locales
export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }))
}

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: { locale: any } // Ensure this is correctly typed
}) {
  const { locale } = params // Destructure locale from params
  unstable_setRequestLocale(locale)

  // Fetch messages for the current locale
  const messages = await getMessages(locale) // Ensure getMessages accepts a locale string

  return (
    <html lang={locale}>
      <body className={outfit.className}>
        <NextIntlClientProvider messages={messages}>
          <Navbar />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
