import type { Metadata } from "next"
import "../globals.css"
import { Outfit } from "next/font/google"
import { NextIntlClientProvider } from "next-intl"
import { getMessages } from "next-intl/server"
import { routing } from "@/i18n/routing"
import { unstable_setRequestLocale } from "next-intl/server"

// PrimeReact CSS imports
import "primereact/resources/themes/saga-blue/theme.css"

// Components
import Navbar from "../components/Navbar"

// Define the type for Locale
type Locale = (typeof routing.locales)[number]

const outfit = Outfit({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

// Generate static params for locales
export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }))
}

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: { locale: Locale } // Ensure locale is correctly typed
}) {
  const { locale } = params

  console.log("Current Locale:", locale) // Debugging line

  // Pass the locale as a string to unstable_setRequestLocale
  unstable_setRequestLocale(locale) // Pass locale directly as a string

  // Fetch messages for the current locale
  const messages = await getMessages({ locale })

  return (
    <html lang={locale}>
      <body className={outfit.className}>
        <NextIntlClientProvider messages={messages}>
          <Navbar />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
